version: '3'

services:
  database:
    build:
      context: ./DataBase
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  javaservice:
    build:
      context: ./JavaService
    depends_on:
      - database
    environment:
      - DISPLAY=${DISPLAY}
      - NO_AT_BRIDGE=1
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri

